#!/bin/zsh
set -e -u

# Taste some classes of devices for their Morello nature.  Specifically, the
# first partition of every sd block device coming to us over USB over a route
# that ends in 3 and usb-serial TTY device whose route ends in .1 or .2.  We
# do this in a somewhat messy way because udev rules are only so powerful:
# we look for the matching route information to decide to taste, and then we
# start over and look for the innermost USB hub for tasting.
cat <<-HERE
### THIS FILE IS AUTOMATICALLY GENERATED BY cluster-to-udev.sh

KERNEL=="sd*1", SUBSYSTEM=="block", \\
  DRIVERS=="usb-storage", KERNELS=="*.3:*", GOTO="morello-taste"
KERNEL=="ttyUSB*", SUBSYSTEM=="tty", \\
  SUBSYSTEMS=="usb", KERNELS=="*.1:*", GOTO="morello-taste"
KERNEL=="ttyUSB*", SUBSYSTEM=="tty", \\
  SUBSYSTEMS=="usb", KERNELS=="*.2:*", GOTO="morello-taste"
GOTO="morello-notaste"
LABEL="morello-taste"
DRIVERS=="usb", ATTRS{bDeviceClass}=="09", \\
  PROGRAM="/usr/local/sbin/udev-morello-hub.sh %S %s{busnum}-%s{devpath}", \\
  ENV{MORELLO_SERIAL}="%c"
LABEL="morello-notaste"
HERE

# Now some rules that match up morello serial numbers with devices.
exec 3< <(jq -c '.machines | .[]')
while read -u 3 machine; do
	exec 4< <(jq -r '.hostname, ."MCC-serno"' <<<"$machine")
	read -u 4 M
	read -u 4 SD

	cat <<-HERE

	# Morello ${M}
	KERNEL=="sd*1", SUBSYSTEM=="block", ENV{MORELLO_SERIAL}=="${SD}" \\
	  SYMLINK+="morello/${M}/mccsd"
	SUBSYSTEM=="tty", ENV{MORELLO_SERIAL}=="${SD}", GOTO="uart"
	GOTO="uart-end"
	LABEL="uart"
	SUBSYSTEMS=="usb", KERNELS=="*.1:*", GOTO="uart-a"
	SUBSYSTEMS=="usb", KERNELS=="*.2:*", GOTO="uart-b"
	GOTO="uart-end"
	LABEL="uart-a"
	GROUP="morello-auto", MODE="0660"
	ATTRS{bInterfaceNumber}=="00", SYMLINK+="morello/${M}/tty-mcc"
	ATTRS{bInterfaceNumber}=="01", SYMLINK+="morello/${M}/tty-pcc"
	ATTRS{bInterfaceNumber}=="02", SYMLINK+="morello/${M}/tty-ap0"
	ATTRS{bInterfaceNumber}=="03", SYMLINK+="morello/${M}/tty-scp"
	GOTO="uart-end"
	LABEL="uart-b"
	GROUP="morello-auto", MODE="0660"
	ATTRS{bInterfaceNumber}=="00", SYMLINK+="morello/${M}/tty-mcp"
	ATTRS{bInterfaceNumber}=="01", SYMLINK+="morello/${M}/tty-fp0"
	ATTRS{bInterfaceNumber}=="02", SYMLINK+="morello/${M}/tty-fp1"
	ATTRS{bInterfaceNumber}=="03", SYMLINK+="morello/${M}/tty-ap2"
	LABEL="uart-end"
	HERE

	exec 4<& -
done
