# This is the local drop-in for the morello-worker@ systemd template.  Install
# it as /etc/systemd/system/morello-worker@.service.d/env-script.conf .

[Unit]
After=tank-morello-scripts.mount 

Requires=tank-morello-export.mount
After=tank-morello-export.mount

[Service]
Environment=MORELLO_SCRIPTS=/tank/morello/scripts
EnvironmentFile=/tank/morello/scripts/local/morello-worker@.env
