# Install me as /etc/squid/conf.d/morello.conf, for example

maximum_object_size 1 GB
cache_dir ufs /var/spool/squid 40000 16 256

connect_retries 5
retry_on_error on
collapsed_forwarding on

acl morellonet src 10.0.0.0/24
http_access allow morellonet
